basePath: /
definitions:
  logic.Post:
    properties:
      published_at:
        type: string
      source:
        type: string
      title:
        example: golang
        type: string
      url:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: David Gagnon
  description: A concurrent search engine for developers.
  title: GRIP Aggregator API
  version: "1.0"
paths:
  /:
    get:
      description: Returns the top 20 newest posts. Detects 'Accept' header for JSON/HTML
        toggle.
      parameters:
      - description: Search Keyword (defaults to 'golang')
        in: query
        name: q
        type: string
      produces:
      - application/json
      - text/html
      responses:
        "200":
          description: Successfully retrieved posts
          schema:
            items:
              $ref: '#/definitions/logic.Post'
            type: array
        "400":
          description: 'Bad Request: Invalid query parameters'
          schema:
            type: string
        "500":
          description: 'Internal Server Error: Template or JSON encoding failed'
          schema:
            type: string
        "504":
          description: 'Gateway Timeout: All sources failed to respond within 2s'
          schema:
            type: string
      summary: Search Aggregated Blogs
swagger: "2.0"
